USE [master]
GO
/****** Object:  Database [ItalianResturant]    Script Date: 12/16/2019 4:07:59 AM ******/
CREATE DATABASE [ItalianResturant]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ItalianResturant_Data', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\ItalianResturant.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'ItalianResturant_Log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\ItalianResturant.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [ItalianResturant] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ItalianResturant].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [ItalianResturant] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [ItalianResturant] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [ItalianResturant] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [ItalianResturant] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [ItalianResturant] SET ARITHABORT OFF 
GO
ALTER DATABASE [ItalianResturant] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [ItalianResturant] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [ItalianResturant] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [ItalianResturant] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [ItalianResturant] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [ItalianResturant] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [ItalianResturant] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [ItalianResturant] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [ItalianResturant] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [ItalianResturant] SET  DISABLE_BROKER 
GO
ALTER DATABASE [ItalianResturant] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [ItalianResturant] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [ItalianResturant] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [ItalianResturant] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [ItalianResturant] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [ItalianResturant] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [ItalianResturant] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [ItalianResturant] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [ItalianResturant] SET  MULTI_USER 
GO
ALTER DATABASE [ItalianResturant] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [ItalianResturant] SET DB_CHAINING OFF 
GO
ALTER DATABASE [ItalianResturant] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [ItalianResturant] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [ItalianResturant] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [ItalianResturant] SET QUERY_STORE = OFF
GO
USE [ItalianResturant]
GO
/****** Object:  Table [dbo].[Admin]    Script Date: 12/16/2019 4:08:00 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Admin](
	[UserName] [varchar](50) NULL,
	[UserPassword] [varchar](50) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Mail]    Script Date: 12/16/2019 4:08:00 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Mail](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](50) NULL,
	[Email] [varchar](50) NULL,
	[Phone] [varchar](50) NULL,
	[Subject] [varchar](50) NULL,
	[Message] [varchar](50) NULL,
 CONSTRAINT [PK_Mail] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Salary]    Script Date: 12/16/2019 4:08:00 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Salary](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](50) NULL,
	[Salary] [int] NULL,
	[PayDate] [varchar](50) NULL,
 CONSTRAINT [PK_Salary] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Staff]    Script Date: 12/16/2019 4:08:00 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Staff](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](50) NULL,
	[Designation] [varchar](50) NULL,
	[Doj] [varchar](50) NULL,
	[Address] [varchar](50) NULL,
	[Contact] [varchar](50) NULL,
 CONSTRAINT [PK_Staff] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
INSERT [dbo].[Admin] ([UserName], [UserPassword]) VALUES (N'Admin@gmail.com', N'admin')
GO
USE [master]
GO
ALTER DATABASE [ItalianResturant] SET  READ_WRITE 
GO
